### ISSUE TITLE
AssetLocator is moved in 0.11

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion.github.io#14]
Hey,

Just thought I'd add a note that the `com.github.dandelion.core.asset.locator.spi.AssetLocator` has moved in 0.11, so that the documentation will get updated when 0.11 is released. The new path is `com.github.dandelion.core.asset.locator.AssetLocator`.

**Comment by tduchateau** [comment]
Thanks Blystad :-)
Don't worry. A whole new documentation will be available and normally, nothing should be forgotten :-)

=> https://github.com/dandelion/dandelion/tree/wip/0.11.0/dandelion-docs
